# Framebuffer display clock generated by pll_hdmi for 1920x1080p60.
create_clock -period 6.723 hdmi_tx_slow_clk

# Pixel and DDR/RISC-V clocks communicate only through explicit CDC blocks.
set_clock_groups -group {hdmi_tx_slow_clk}
