# Framebuffer display clock generated by pll_hdmi for 1280x720p60 (74.25 MHz).
create_clock -period 13.468 hdmi_tx_slow_clk

# Pixel and DDR/RISC-V clocks communicate only through explicit CDC blocks.
set_clock_groups -group {hdmi_tx_slow_clk}
