

# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2024.1.163
# Date: 2024-07-09 19:18

# Copyright (C) 2013 - 2024 Efinix Inc. All rights reserved.

# Device: Ti60F225
# Project: carrychain_prj
# Timing Model: I3 (final)

# PLL Constraints
#################
create_clock -period 10.0000 clk_100m
create_clock -waveform {0.4167 1.2500} -period 1.6667 clk_600m
create_clock -period 3.3333 clk_300m

# JTAG Constraints
####################
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_TCK}]
set_output_delay -clock jtag_inst1_TCK -max 1.519 [get_ports {jtag_inst1_TDO}]
set_output_delay -clock jtag_inst1_TCK -min 0.495 [get_ports {jtag_inst1_TDO}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.144 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.077 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.759 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.401 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.234 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.025 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.176 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.074 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.197 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.055 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 1.190 [get_ports {jtag_inst1_DRCK}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.620 [get_ports {jtag_inst1_DRCK}]
# JTAG Constraints (extra... not used by current Efinity debug tools)
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_DRCK}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.169 [get_ports {jtag_inst1_RUNTEST}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.066 [get_ports {jtag_inst1_RUNTEST}]
# Create separate clock groups for JTAG clocks. Remove DRCK clock from the list below if it is not defined.
# set_clock_groups -asynchronous -group {jtag_inst1_TCK jtag_inst1_DRCK}

# HSIO GPIO Constraints
#########################
create_clock -period <USER_PERIOD> [get_ports {clk}]

# LVDS Rx Constraints
#######################
set_input_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -max 0.589 [get_ports {lvds_rx_RX_DATA[*]}]
set_input_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -min 0.342 [get_ports {lvds_rx_RX_DATA[*]}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -max 0.362 [get_ports {lvds_rx_RX_RST}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -min -0.140 [get_ports {lvds_rx_RX_RST}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -max 0.290 [get_ports {lvds_rx_RX_DLY_ENA}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -min -0.140 [get_ports {lvds_rx_RX_DLY_ENA}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -max 0.290 [get_ports {lvds_rx_RX_DLY_INC}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -min -0.140 [get_ports {lvds_rx_RX_DLY_INC}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -max 0.362 [get_ports {lvds_rx_RX_DLY_RST}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~152~322}] -min -0.140 [get_ports {lvds_rx_RX_DLY_RST}]

# LVDS Tx Constraints
#######################
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~79~322}] -max 0.435 [get_ports {lvds_tx_TX_DATA[*]}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~79~322}] -min -0.140 [get_ports {lvds_tx_TX_DATA[*]}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~79~322}] -max 0.435 [get_ports {lvds_tx_TX_OE}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~79~322}] -min -0.140 [get_ports {lvds_tx_TX_OE}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~79~322}] -max 0.483 [get_ports {lvds_tx_TX_RST}]
set_output_delay -clock clk_300m -reference_pin [get_ports {clk_300m~CLKOUT~79~322}] -min -0.175 [get_ports {lvds_tx_TX_RST}]
set_false_path -from [get_ports {lvds_rx_RX_DATA[*]}] -to clk_300m
# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 0.914> [get_ports {clk_100m}]
# set_clock_latency -source -hold <board_min + 0.530> [get_ports {clk_100m}]
# set_clock_latency -source -setup <board_max + 0.914> [get_ports {clk_600m}]
# set_clock_latency -source -hold <board_min + 0.530> [get_ports {clk_600m}]
# set_clock_latency -source -setup <board_max + 0.914> [get_ports {clk_300m}]
# set_clock_latency -source -hold <board_min + 0.530> [get_ports {clk_300m}]
# set_clock_latency -source -setup <board_max + 0.953> [get_ports {clk}]
# set_clock_latency -source -hold <board_min + 0.552> [get_ports {clk}]


#set_min_delay 6.0 -from [get_cells send_en_r_lock~FF] -to [get_cells lvds_tx_TX_DATA[0]~FF]
#set_max_delay 10.0 -from [get_cells send_en_r_lock~FF] -to [get_cells lvds_tx_TX_DATA[0]~FF]