
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2024.1.163.4.11
# Date: 2024-11-27 18:53

# Copyright (C) 2013 - 2024 Efinix Inc. All rights reserved.

# Device: Ti60F225
# Project: led_test
# Timing Model: I3 (final)

# Oscillator Constraints
########################
create_clock -period 100 [get_ports {osc_inst1_CLKOUT}]

# PLL Constraints
#################
create_clock -period 8.0000 FB
create_clock -waveform {2.0000 6.0000} -period 8.0000 ge1_tx_clk_90
create_clock -period 8.0000 ge1_tx_clk
create_clock -period 8.0000 rx_pll_CLKOUT0
create_clock -waveform {2.0000 6.0000} -period 8.0000 ge0_tx_clk
create_clock -waveform {2.0000 6.0000} -period 8.0000 ge0_tx_clk_90
create_clock -period 8.0 [get_ports {rxc}]
create_clock -period 8.0 [get_ports {rxc1}]
# GPIO Constraints
####################
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {phy_rst_n}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {phy_rst_n}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {phy_rst_n1}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {phy_rst_n1}]

# HSIO GPIO Constraints
#########################
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~146}] -max 0.476 [get_ports {rx_dv_LO rx_dv_HI}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~146}] -min 0.276 [get_ports {rx_dv_LO rx_dv_HI}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~293}] -max 0.476 [get_ports {rx_dv1_LO rx_dv1_HI}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~293}] -min 0.276 [get_ports {rx_dv1_LO rx_dv1_HI}]
create_clock -period <USER_PERIOD> [get_ports {rxc}]
create_clock -period <USER_PERIOD> [get_ports {rxc1}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~277}] -max 0.476 [get_ports {rxd1_LO[0] rxd1_HI[0]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~277}] -min 0.276 [get_ports {rxd1_LO[0] rxd1_HI[0]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~278}] -max 0.476 [get_ports {rxd1_LO[1] rxd1_HI[1]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~278}] -min 0.276 [get_ports {rxd1_LO[1] rxd1_HI[1]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~267}] -max 0.476 [get_ports {rxd1_LO[2] rxd1_HI[2]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~267}] -min 0.276 [get_ports {rxd1_LO[2] rxd1_HI[2]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~222}] -max 0.476 [get_ports {rxd1_LO[3] rxd1_HI[3]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~222}] -min 0.276 [get_ports {rxd1_LO[3] rxd1_HI[3]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~129}] -max 0.476 [get_ports {rxd_lo_i[0] rxd_hi_i[0]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~129}] -min 0.276 [get_ports {rxd_lo_i[0] rxd_hi_i[0]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~113}] -max 0.476 [get_ports {rxd_lo_i[1] rxd_hi_i[1]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~113}] -min 0.276 [get_ports {rxd_lo_i[1] rxd_hi_i[1]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~12}] -max 0.476 [get_ports {rxd_lo_i[2] rxd_hi_i[2]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~12}] -min 0.276 [get_ports {rxd_lo_i[2] rxd_hi_i[2]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~96}] -max 0.476 [get_ports {rxd_lo_i[3] rxd_hi_i[3]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~96}] -min 0.276 [get_ports {rxd_lo_i[3] rxd_hi_i[3]}]
set_output_delay -clock osc_inst1_CLKOUT -reference_pin [get_ports {osc_inst1_CLKOUT~CLKOUT~1~181}] -max 0.302 [get_ports {mdc_o}]
set_output_delay -clock osc_inst1_CLKOUT -reference_pin [get_ports {osc_inst1_CLKOUT~CLKOUT~1~181}] -min -0.140 [get_ports {mdc_o}]
set_output_delay -clock osc_inst1_CLKOUT -reference_pin [get_ports {osc_inst1_CLKOUT~CLKOUT~1~195}] -max 0.302 [get_ports {mdc_o1}]
set_output_delay -clock osc_inst1_CLKOUT -reference_pin [get_ports {osc_inst1_CLKOUT~CLKOUT~1~195}] -min -0.140 [get_ports {mdc_o1}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~15}] -max 0.302 [get_ports {tx_en_o_LO tx_en_o_HI}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~15}] -min -0.140 [get_ports {tx_en_o_LO tx_en_o_HI}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~223}] -max 0.302 [get_ports {tx_en_o1_LO tx_en_o1_HI}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~223}] -min -0.140 [get_ports {tx_en_o1_LO tx_en_o1_HI}]
set_output_delay -clock ge0_tx_clk_90 -reference_pin [get_ports {ge0_tx_clk_90~CLKOUT~1~130}] -max 0.302 [get_ports {txc_lo_o txc_hi_o}]
set_output_delay -clock ge0_tx_clk_90 -reference_pin [get_ports {ge0_tx_clk_90~CLKOUT~1~130}] -min -0.140 [get_ports {txc_lo_o txc_hi_o}]
set_output_delay -clock ge1_tx_clk_90 -reference_pin [get_ports {ge1_tx_clk_90~CLKOUT~1~268}] -max 0.302 [get_ports {txc1_LO txc1_HI}]
set_output_delay -clock ge1_tx_clk_90 -reference_pin [get_ports {ge1_tx_clk_90~CLKOUT~1~268}] -min -0.140 [get_ports {txc1_LO txc1_HI}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~257}] -max 0.302 [get_ports {txd1_LO[0] txd1_HI[0]}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~257}] -min -0.140 [get_ports {txd1_LO[0] txd1_HI[0]}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~245}] -max 0.302 [get_ports {txd1_LO[1] txd1_HI[1]}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~245}] -min -0.140 [get_ports {txd1_LO[1] txd1_HI[1]}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~246}] -max 0.302 [get_ports {txd1_LO[2] txd1_HI[2]}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~246}] -min -0.140 [get_ports {txd1_LO[2] txd1_HI[2]}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~171}] -max 0.302 [get_ports {txd1_LO[3] txd1_HI[3]}]
set_output_delay -clock ge1_tx_clk -reference_pin [get_ports {ge1_tx_clk~CLKOUT~1~171}] -min -0.140 [get_ports {txd1_LO[3] txd1_HI[3]}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~114}] -max 0.302 [get_ports {txd_lo_o[0] txd_hi_o[0]}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~114}] -min -0.140 [get_ports {txd_lo_o[0] txd_hi_o[0]}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~97}] -max 0.302 [get_ports {txd_lo_o[1] txd_hi_o[1]}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~97}] -min -0.140 [get_ports {txd_lo_o[1] txd_hi_o[1]}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~206}] -max 0.302 [get_ports {txd_lo_o[2] txd_hi_o[2]}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~206}] -min -0.140 [get_ports {txd_lo_o[2] txd_hi_o[2]}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~207}] -max 0.302 [get_ports {txd_lo_o[3] txd_hi_o[3]}]
set_output_delay -clock ge0_tx_clk -reference_pin [get_ports {ge0_tx_clk~CLKOUT~1~207}] -min -0.140 [get_ports {txd_lo_o[3] txd_hi_o[3]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_i}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_i}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_o}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_o}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_oe}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_oe}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_i1}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_i1}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_o1}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_o1}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_oe1}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_oe1}]

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 4.124> [get_ports {FB}]
# set_clock_latency -source -hold <board_min + 2.360> [get_ports {FB}]
# set_clock_latency -source -setup <board_max + 4.124> [get_ports {ge1_tx_clk_90}]
# set_clock_latency -source -hold <board_min + 2.360> [get_ports {ge1_tx_clk_90}]
# set_clock_latency -source -setup <board_max + 4.124> [get_ports {ge1_tx_clk}]
# set_clock_latency -source -hold <board_min + 2.360> [get_ports {ge1_tx_clk}]
# set_clock_latency -source -setup <board_max + 1.053> [get_ports {rx_pll_CLKOUT0}]
# set_clock_latency -source -hold <board_min + 0.609> [get_ports {rx_pll_CLKOUT0}]
# set_clock_latency -source -setup <board_max + 1.053> [get_ports {ge0_tx_clk}]
# set_clock_latency -source -hold <board_min + 0.609> [get_ports {ge0_tx_clk}]
# set_clock_latency -source -setup <board_max + 1.053> [get_ports {ge0_tx_clk_90}]
# set_clock_latency -source -hold <board_min + 0.609> [get_ports {ge0_tx_clk_90}]
# set_clock_latency -source -setup <board_max + 0.953> [get_ports {rxc}]
# set_clock_latency -source -hold <board_min + 0.552> [get_ports {rxc}]
# set_clock_latency -source -setup <board_max + 2.039> [get_ports {rxc1}]
# set_clock_latency -source -hold <board_min + 1.182> [get_ports {rxc1}]
