
# Efinity Interface Designer SDC
# Version: 2021.2.316
# Date: 2021-12-07 12:40

# Copyright (C) 2017 - 2021 Efinix Inc. All rights reserved.

# Device: Ti60F225
# Project: DDR3_MC
# Timing Model: C4 (preliminary)
#               NOTE: The timing data is not final

# PLL Constraints
#################
create_clock -period 9.26 sys_clk
create_clock -period 2.50 tdqss_clk
create_clock -period 5.00 core_clk
create_clock -period 2.50 tac_clk
create_clock -waveform {0.625 1.875} -period 2.50 twd_clk

create_clock -period 2.6891 hdmi_rx_fast_clk
create_clock -period 2.6891 hdmi_tx_fast_clk
create_clock -period 13.4454 hdmi_rx_slow_clk


create_clock -period 8.0000 clk_125m
create_clock -period 8.0000 rx_pll_CLKOUT0
create_clock -waveform {2.0000 6.0000} -period 8.0000 ge0_tx_clk
create_clock -waveform {2.0000 6.0000} -period 8.0000 ge0_tx_clk_90
set_clock_groups -exclusive -group {twd_clk} -group {sys_clk} -group {tac_clk} -group {tdqss_clk} -group {core_clk} -group {jtag_inst1_TCK} -group {hdmi_rx_slow_clk}

#set_false_path -from [get_clocks twd_clk] -to [get_clocks core_clk]
#set_false_path -from [get_clocks tac_clk] -to [get_clocks core_clk]
#set_false_path -from [get_clocks tdqss_clk] -to [get_clocks core_clk]






# GPIO Constraints
####################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {hdmi_sel}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {hdmi_sel}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {nrst}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {nrst}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {b_led[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {b_led[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {b_led[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {b_led[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {phy_rst_n}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {phy_rst_n}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {phy_rst_n1}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {phy_rst_n1}]

# JTAG Constraints
####################
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_TCK}]
set_output_delay -clock jtag_inst1_TCK -max 0.134 [get_ports {jtag_inst1_TDO}]
set_output_delay -clock jtag_inst1_TCK -min -0.075 [get_ports {jtag_inst1_TDO}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.322 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.187 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.322 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.187 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.279 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.162 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.322 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.187 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.388 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.225 [get_ports {jtag_inst1_SHIFT}]
# JTAG Constraints (extra... not used by current Efinity debug tools)
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_DRCK}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.322 [get_ports {jtag_inst1_RUNTEST}]
# set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.187 [get_ports {jtag_inst1_RUNTEST}]
# Create separate clock groups for JTAG clocks. Remove DRCK clock from the list below if it is not defined.
# set_clock_groups -asynchronous -group {jtag_inst1_TCK jtag_inst1_DRCK}

# HSIO GPIO Constraints
#########################
create_clock -period 40.000 [get_ports {clk_25m}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {HDMI_5V_N}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {HDMI_5V_N}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~146}] -max 0.476 [get_ports {rx_dv_LO rx_dv}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~146}] -min 0.276 [get_ports {rx_dv_LO rx_dv}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~293}] -max 0.476 [get_ports {rx_dv1_LO rx_dv1_HI}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~293}] -min 0.276 [get_ports {rx_dv1_LO rx_dv1_HI}]
create_clock -period 8.0 [get_ports {rxc}]
create_clock -period 8.0 [get_ports {rxc1}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~277}] -max 0.476 [get_ports {rxd1_LO[0] rxd1_HI[0]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~277}] -min 0.276 [get_ports {rxd1_LO[0] rxd1_HI[0]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~278}] -max 0.476 [get_ports {rxd1_LO[1] rxd1_HI[1]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~278}] -min 0.276 [get_ports {rxd1_LO[1] rxd1_HI[1]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~267}] -max 0.476 [get_ports {rxd1_LO[2] rxd1_HI[2]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~267}] -min 0.276 [get_ports {rxd1_LO[2] rxd1_HI[2]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~222}] -max 0.476 [get_ports {rxd1_LO[3] rxd1_HI[3]}]
set_input_delay -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~222}] -min 0.276 [get_ports {rxd1_LO[3] rxd1_HI[3]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~129}] -max 0.476 [get_ports {rxd_lo_i[0] rxd_hi_i[0]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~129}] -min 0.276 [get_ports {rxd_lo_i[0] rxd_hi_i[0]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~113}] -max 0.476 [get_ports {rxd_lo_i[1] rxd_hi_i[1]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~113}] -min 0.276 [get_ports {rxd_lo_i[1] rxd_hi_i[1]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~12}] -max 0.476 [get_ports {rxd_lo_i[2] rxd_hi_i[2]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~12}] -min 0.276 [get_ports {rxd_lo_i[2] rxd_hi_i[2]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~96}] -max 0.476 [get_ports {rxd_lo_i[3] rxd_hi_i[3]}]
set_input_delay -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~96}] -min 0.276 [get_ports {rxd_lo_i[3] rxd_hi_i[3]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {uart_rx}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {uart_rx}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~95}] -max 0.302 [get_ports {addr[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~95}] -min -0.140 [get_ports {addr[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~36}] -max 0.302 [get_ports {addr[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~36}] -min -0.140 [get_ports {addr[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~70}] -max 0.302 [get_ports {addr[2]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~70}] -min -0.140 [get_ports {addr[2]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~50~1}] -max 0.302 [get_ports {addr[3]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~50~1}] -min -0.140 [get_ports {addr[3]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~25}] -max 0.302 [get_ports {addr[4]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~25}] -min -0.140 [get_ports {addr[4]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~142~1}] -max 0.302 [get_ports {addr[5]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~142~1}] -min -0.140 [get_ports {addr[5]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~59}] -max 0.302 [get_ports {addr[6]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~59}] -min -0.140 [get_ports {addr[6]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~110}] -max 0.302 [get_ports {addr[7]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~110}] -min -0.140 [get_ports {addr[7]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~26}] -max 0.302 [get_ports {addr[8]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~26}] -min -0.140 [get_ports {addr[8]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~127}] -max 0.302 [get_ports {addr[9]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~127}] -min -0.140 [get_ports {addr[9]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~138}] -max 0.302 [get_ports {addr[10]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~138}] -min -0.140 [get_ports {addr[10]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~60}] -max 0.302 [get_ports {addr[11]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~60}] -min -0.140 [get_ports {addr[11]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~35}] -max 0.302 [get_ports {addr[12]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~35}] -min -0.140 [get_ports {addr[12]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~71}] -max 0.302 [get_ports {addr[13]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~71}] -min -0.140 [get_ports {addr[13]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~109}] -max 0.302 [get_ports {addr[14]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~109}] -min -0.140 [get_ports {addr[14]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~143~1}] -max 0.302 [get_ports {addr[15]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~143~1}] -min -0.140 [get_ports {addr[15]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~74~1}] -max 0.302 [get_ports {ba[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~74~1}] -min -0.140 [get_ports {ba[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~132~1}] -max 0.302 [get_ports {ba[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~132~1}] -min -0.140 [get_ports {ba[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~126}] -max 0.302 [get_ports {ba[2]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~126}] -min -0.140 [get_ports {ba[2]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~49}] -max 0.302 [get_ports {cas}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~49}] -min -0.140 [get_ports {cas}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~123~1}] -max 0.302 [get_ports {cke}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~123~1}] -min -0.140 [get_ports {cke}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~95~1}] -max 0.302 [get_ports {cs}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~95~1}] -min -0.140 [get_ports {cs}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~131~1}] -max 0.302 [get_ports {o_dm_lo[0] o_dm_hi[0]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~131~1}] -min -0.140 [get_ports {o_dm_lo[0] o_dm_hi[0]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~83~1}] -max 0.302 [get_ports {o_dm_lo[1] o_dm_hi[1]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~83~1}] -min -0.140 [get_ports {o_dm_lo[1] o_dm_hi[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {HPD_N}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {HPD_N}]
set_output_delay -clock clk_10m -reference_pin [get_ports {clk_10m~CLKOUT~1~195}] -max 0.302 [get_ports {mdc_o_LO mdc_o_HI}]
set_output_delay -clock clk_10m -reference_pin [get_ports {clk_10m~CLKOUT~1~195}] -min -0.140 [get_ports {mdc_o_LO mdc_o_HI}]
set_output_delay -clock clk_10m -reference_pin [get_ports {clk_10m~CLKOUT~1~181}] -max 0.302 [get_ports {mdc_o1_LO mdc_o1_HI}]
set_output_delay -clock clk_10m -reference_pin [get_ports {clk_10m~CLKOUT~1~181}] -min -0.140 [get_ports {mdc_o1_LO mdc_o1_HI}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~73~1}] -max 0.302 [get_ports {odt}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~73~1}] -min -0.140 [get_ports {odt}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~48}] -max 0.302 [get_ports {ras}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~48}] -min -0.140 [get_ports {ras}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~139}] -max 0.302 [get_ports {reset}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~139}] -min -0.140 [get_ports {reset}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~15}] -max 0.302 [get_ports {tx_en_o_LO tx_en_o_HI}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~15}] -min -0.140 [get_ports {tx_en_o_LO tx_en_o_HI}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~223}] -max 0.302 [get_ports {tx_en_o1_LO tx_en_o1_HI}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~223}] -min -0.140 [get_ports {tx_en_o1_LO tx_en_o1_HI}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~130}] -max 0.302 [get_ports {txc_lo_o txc_hi_o}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~130}] -min -0.140 [get_ports {txc_lo_o txc_hi_o}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~268}] -max 0.302 [get_ports {txc1_LO txc1_HI}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~268}] -min -0.140 [get_ports {txc1_LO txc1_HI}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~257}] -max 0.302 [get_ports {txd1_LO[0] txd1_HI[0]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~257}] -min -0.140 [get_ports {txd1_LO[0] txd1_HI[0]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~245}] -max 0.302 [get_ports {txd1_LO[1] txd1_HI[1]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~245}] -min -0.140 [get_ports {txd1_LO[1] txd1_HI[1]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~246}] -max 0.302 [get_ports {txd1_LO[2] txd1_HI[2]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~246}] -min -0.140 [get_ports {txd1_LO[2] txd1_HI[2]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~171}] -max 0.302 [get_ports {txd1_LO[3] txd1_HI[3]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~171}] -min -0.140 [get_ports {txd1_LO[3] txd1_HI[3]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~114}] -max 0.302 [get_ports {txd_lo_o[0] txd_hi_o[0]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~114}] -min -0.140 [get_ports {txd_lo_o[0] txd_hi_o[0]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~97}] -max 0.302 [get_ports {txd_lo_o[1] txd_hi_o[1]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~97}] -min -0.140 [get_ports {txd_lo_o[1] txd_hi_o[1]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~206}] -max 0.302 [get_ports {txd_lo_o[2] txd_hi_o[2]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~206}] -min -0.140 [get_ports {txd_lo_o[2] txd_hi_o[2]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~207}] -max 0.302 [get_ports {txd_lo_o[3] txd_hi_o[3]}]
set_output_delay -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~207}] -min -0.140 [get_ports {txd_lo_o[3] txd_hi_o[3]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {uart_tx}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {uart_tx}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~94}] -max 0.302 [get_ports {we}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~94}] -min -0.140 [get_ports {we}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~148~1}] -max 0.476 [get_ports {i_dq_lo[0] i_dq_hi[0]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~148~1}] -min 0.276 [get_ports {i_dq_lo[0] i_dq_hi[0]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~150~1}] -max 0.302 [get_ports {o_dq_lo[0] o_dq_hi[0]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~150~1}] -min -0.140 [get_ports {o_dq_lo[0] o_dq_hi[0]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~150~1}] -max 0.302 [get_ports {o_dq_oe[0]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~150~1}] -min -0.140 [get_ports {o_dq_oe[0]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~157~1}] -max 0.476 [get_ports {i_dq_lo[1] i_dq_hi[1]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~157~1}] -min 0.276 [get_ports {i_dq_lo[1] i_dq_hi[1]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~159~1}] -max 0.302 [get_ports {o_dq_lo[1] o_dq_hi[1]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~159~1}] -min -0.140 [get_ports {o_dq_lo[1] o_dq_hi[1]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~159~1}] -max 0.302 [get_ports {o_dq_oe[1]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~159~1}] -min -0.140 [get_ports {o_dq_oe[1]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~164~1}] -max 0.476 [get_ports {i_dq_lo[2] i_dq_hi[2]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~164~1}] -min 0.276 [get_ports {i_dq_lo[2] i_dq_hi[2]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~166~1}] -max 0.302 [get_ports {o_dq_lo[2] o_dq_hi[2]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~166~1}] -min -0.140 [get_ports {o_dq_lo[2] o_dq_hi[2]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~166~1}] -max 0.302 [get_ports {o_dq_oe[2]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~166~1}] -min -0.140 [get_ports {o_dq_oe[2]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~149~1}] -max 0.476 [get_ports {i_dq_lo[3] i_dq_hi[3]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~149~1}] -min 0.276 [get_ports {i_dq_lo[3] i_dq_hi[3]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~151~1}] -max 0.302 [get_ports {o_dq_lo[3] o_dq_hi[3]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~151~1}] -min -0.140 [get_ports {o_dq_lo[3] o_dq_hi[3]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~151~1}] -max 0.302 [get_ports {o_dq_oe[3]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~151~1}] -min -0.140 [get_ports {o_dq_oe[3]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~189~1}] -max 0.476 [get_ports {i_dq_lo[4] i_dq_hi[4]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~189~1}] -min 0.276 [get_ports {i_dq_lo[4] i_dq_hi[4]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~191~1}] -max 0.302 [get_ports {o_dq_lo[4] o_dq_hi[4]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~191~1}] -min -0.140 [get_ports {o_dq_lo[4] o_dq_hi[4]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~191~1}] -max 0.302 [get_ports {o_dq_oe[4]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~191~1}] -min -0.140 [get_ports {o_dq_oe[4]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~156~1}] -max 0.476 [get_ports {i_dq_lo[5] i_dq_hi[5]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~156~1}] -min 0.276 [get_ports {i_dq_lo[5] i_dq_hi[5]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~158~1}] -max 0.302 [get_ports {o_dq_lo[5] o_dq_hi[5]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~158~1}] -min -0.140 [get_ports {o_dq_lo[5] o_dq_hi[5]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~158~1}] -max 0.302 [get_ports {o_dq_oe[5]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~158~1}] -min -0.140 [get_ports {o_dq_oe[5]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~165~1}] -max 0.476 [get_ports {i_dq_lo[6] i_dq_hi[6]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~165~1}] -min 0.276 [get_ports {i_dq_lo[6] i_dq_hi[6]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~167~1}] -max 0.302 [get_ports {o_dq_lo[6] o_dq_hi[6]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~167~1}] -min -0.140 [get_ports {o_dq_lo[6] o_dq_hi[6]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~167~1}] -max 0.302 [get_ports {o_dq_oe[6]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~167~1}] -min -0.140 [get_ports {o_dq_oe[6]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~188~1}] -max 0.476 [get_ports {i_dq_lo[7] i_dq_hi[7]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~188~1}] -min 0.276 [get_ports {i_dq_lo[7] i_dq_hi[7]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~190~1}] -max 0.302 [get_ports {o_dq_lo[7] o_dq_hi[7]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~190~1}] -min -0.140 [get_ports {o_dq_lo[7] o_dq_hi[7]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~190~1}] -max 0.302 [get_ports {o_dq_oe[7]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~190~1}] -min -0.140 [get_ports {o_dq_oe[7]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~82~1}] -max 0.476 [get_ports {i_dq_lo[8] i_dq_hi[8]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~82~1}] -min 0.276 [get_ports {i_dq_lo[8] i_dq_hi[8]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~84~1}] -max 0.302 [get_ports {o_dq_lo[8] o_dq_hi[8]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~84~1}] -min -0.140 [get_ports {o_dq_lo[8] o_dq_hi[8]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~84~1}] -max 0.302 [get_ports {o_dq_oe[8]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~84~1}] -min -0.140 [get_ports {o_dq_oe[8]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~39~1}] -max 0.476 [get_ports {i_dq_lo[9] i_dq_hi[9]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~39~1}] -min 0.276 [get_ports {i_dq_lo[9] i_dq_hi[9]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~41~1}] -max 0.302 [get_ports {o_dq_lo[9] o_dq_hi[9]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~41~1}] -min -0.140 [get_ports {o_dq_lo[9] o_dq_hi[9]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~41~1}] -max 0.302 [get_ports {o_dq_oe[9]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~41~1}] -min -0.140 [get_ports {o_dq_oe[9]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~22~1}] -max 0.476 [get_ports {i_dq_lo[10] i_dq_hi[10]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~22~1}] -min 0.276 [get_ports {i_dq_lo[10] i_dq_hi[10]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~24~1}] -max 0.302 [get_ports {o_dq_lo[10] o_dq_hi[10]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~24~1}] -min -0.140 [get_ports {o_dq_lo[10] o_dq_hi[10]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~24~1}] -max 0.302 [get_ports {o_dq_oe[10]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~24~1}] -min -0.140 [get_ports {o_dq_oe[10]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~92~1}] -max 0.476 [get_ports {i_dq_lo[11] i_dq_hi[11]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~92~1}] -min 0.276 [get_ports {i_dq_lo[11] i_dq_hi[11]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~94~1}] -max 0.302 [get_ports {o_dq_lo[11] o_dq_hi[11]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~94~1}] -min -0.140 [get_ports {o_dq_lo[11] o_dq_hi[11]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~94~1}] -max 0.302 [get_ports {o_dq_oe[11]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~94~1}] -min -0.140 [get_ports {o_dq_oe[11]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~23~1}] -max 0.476 [get_ports {i_dq_lo[12] i_dq_hi[12]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~23~1}] -min 0.276 [get_ports {i_dq_lo[12] i_dq_hi[12]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~25~1}] -max 0.302 [get_ports {o_dq_lo[12] o_dq_hi[12]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~25~1}] -min -0.140 [get_ports {o_dq_lo[12] o_dq_hi[12]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~25~1}] -max 0.302 [get_ports {o_dq_oe[12]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~25~1}] -min -0.140 [get_ports {o_dq_oe[12]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~38~1}] -max 0.476 [get_ports {i_dq_lo[13] i_dq_hi[13]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~38~1}] -min 0.276 [get_ports {i_dq_lo[13] i_dq_hi[13]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~40~1}] -max 0.302 [get_ports {o_dq_lo[13] o_dq_hi[13]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~40~1}] -min -0.140 [get_ports {o_dq_lo[13] o_dq_hi[13]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~40~1}] -max 0.302 [get_ports {o_dq_oe[13]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~40~1}] -min -0.140 [get_ports {o_dq_oe[13]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~11~1}] -max 0.476 [get_ports {i_dq_lo[14] i_dq_hi[14]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~11~1}] -min 0.276 [get_ports {i_dq_lo[14] i_dq_hi[14]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~13~1}] -max 0.302 [get_ports {o_dq_lo[14] o_dq_hi[14]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~13~1}] -min -0.140 [get_ports {o_dq_lo[14] o_dq_hi[14]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~13~1}] -max 0.302 [get_ports {o_dq_oe[14]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~13~1}] -min -0.140 [get_ports {o_dq_oe[14]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~12~1}] -max 0.476 [get_ports {i_dq_lo[15] i_dq_hi[15]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~12~1}] -min 0.276 [get_ports {i_dq_lo[15] i_dq_hi[15]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~14~1}] -max 0.302 [get_ports {o_dq_lo[15] o_dq_hi[15]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~14~1}] -min -0.140 [get_ports {o_dq_lo[15] o_dq_hi[15]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~14~1}] -max 0.302 [get_ports {o_dq_oe[15]}]
set_output_delay -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~14~1}] -min -0.140 [get_ports {o_dq_oe[15]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~172~1}] -max 0.476 [get_ports {i_dqs_lo[0] i_dqs_hi[0]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~172~1}] -min 0.276 [get_ports {i_dqs_lo[0] i_dqs_hi[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~174~1}] -max 0.302 [get_ports {o_dqs_lo[0] o_dqs_hi[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~174~1}] -min -0.140 [get_ports {o_dqs_lo[0] o_dqs_hi[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~174~1}] -max 0.302 [get_ports {o_dqs_oe[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~174~1}] -min -0.140 [get_ports {o_dqs_oe[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~175~1}] -max 0.302 [get_ports {o_dqs_n_oe[0]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~175~1}] -min -0.140 [get_ports {o_dqs_n_oe[0]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~30~1}] -max 0.476 [get_ports {i_dqs_lo[1] i_dqs_hi[1]}]
set_input_delay -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~30~1}] -min 0.276 [get_ports {i_dqs_lo[1] i_dqs_hi[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~32~1}] -max 0.302 [get_ports {o_dqs_lo[1] o_dqs_hi[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~32~1}] -min -0.140 [get_ports {o_dqs_lo[1] o_dqs_hi[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~32~1}] -max 0.302 [get_ports {o_dqs_oe[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~32~1}] -min -0.140 [get_ports {o_dqs_oe[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~33~1}] -max 0.302 [get_ports {o_dqs_n_oe[1]}]
set_output_delay -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~33~1}] -min -0.140 [get_ports {o_dqs_n_oe[1]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_HDMI_SCL_IN}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_HDMI_SCL_IN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_HDMI_SCL_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_HDMI_SCL_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_HDMI_SCL_OE}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_HDMI_SCL_OE}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_HDMI_SDA_IN}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_HDMI_SDA_IN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_HDMI_SDA_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_HDMI_SDA_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {FPGA_HDMI_SDA_OE}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {FPGA_HDMI_SDA_OE}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_i}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_i}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_o}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_o}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_oe}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_oe}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_io1_IN}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_io1_IN}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_io1_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_io1_OUT}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {mdio_io1_OE}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {mdio_io1_OE}]

# LVDS Rx Constraints
#######################
set_input_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~258}] -max 0.589 [get_ports {hdmi_rx_d0_RX_DATA[*]}]
set_input_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~258}] -min 0.342 [get_ports {hdmi_rx_d0_RX_DATA[*]}]
set_input_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~283}] -max 0.589 [get_ports {hdmi_rx_d1_RX_DATA[*]}]
set_input_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~283}] -min 0.342 [get_ports {hdmi_rx_d1_RX_DATA[*]}]
set_input_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~271}] -max 0.589 [get_ports {hdmi_rx_d2_RX_DATA[*]}]
set_input_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~271}] -min 0.342 [get_ports {hdmi_rx_d2_RX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~258}] -max 0.362 [get_ports {hdmi_rx_d0_RX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~258}] -min -0.140 [get_ports {hdmi_rx_d0_RX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~283}] -max 0.362 [get_ports {hdmi_rx_d1_RX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~283}] -min -0.140 [get_ports {hdmi_rx_d1_RX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~271}] -max 0.362 [get_ports {hdmi_rx_d2_RX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~271}] -min -0.140 [get_ports {hdmi_rx_d2_RX_RST}]

# LVDS Tx Constraints
#######################
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~175}] -max 0.435 [get_ports {tmds_tx_clk_TX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~175}] -min -0.140 [get_ports {tmds_tx_clk_TX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~175}] -max 0.435 [get_ports {tmds_tx_clk_TX_OE}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~175}] -min -0.140 [get_ports {tmds_tx_clk_TX_OE}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~215}] -max 0.435 [get_ports {tmds_tx_data0_TX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~215}] -min -0.140 [get_ports {tmds_tx_data0_TX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~215}] -max 0.435 [get_ports {tmds_tx_data0_TX_OE}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~215}] -min -0.140 [get_ports {tmds_tx_data0_TX_OE}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~187}] -max 0.435 [get_ports {tmds_tx_data1_TX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~187}] -min -0.140 [get_ports {tmds_tx_data1_TX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~187}] -max 0.435 [get_ports {tmds_tx_data1_TX_OE}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~187}] -min -0.140 [get_ports {tmds_tx_data1_TX_OE}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~200}] -max 0.435 [get_ports {tmds_tx_data2_TX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~200}] -min -0.140 [get_ports {tmds_tx_data2_TX_DATA[*]}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~200}] -max 0.435 [get_ports {tmds_tx_data2_TX_OE}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~200}] -min -0.140 [get_ports {tmds_tx_data2_TX_OE}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~175}] -max 0.483 [get_ports {tmds_tx_clk_TX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~175}] -min -0.175 [get_ports {tmds_tx_clk_TX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~215}] -max 0.483 [get_ports {tmds_tx_data0_TX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~215}] -min -0.175 [get_ports {tmds_tx_data0_TX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~187}] -max 0.483 [get_ports {tmds_tx_data1_TX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~187}] -min -0.175 [get_ports {tmds_tx_data1_TX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~200}] -max 0.483 [get_ports {tmds_tx_data2_TX_RST}]
set_output_delay -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~200}] -min -0.175 [get_ports {tmds_tx_data2_TX_RST}]

# Clockout Interface
######################
# addr[0] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~95}]
# addr[10] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~138}]
# addr[11] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~60}]
# addr[12] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~35}]
# addr[13] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~71}]
# addr[14] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~109}]
# addr[15] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~143~1}]
# addr[1] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~36}]
# addr[2] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~70}]
# addr[3] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~50~1}]
# addr[4] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~25}]
# addr[5] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~142~1}]
# addr[6] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~59}]
# addr[7] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~110}]
# addr[8] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~26}]
# addr[9] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~127}]
# ba[0] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~74~1}]
# ba[1] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~132~1}]
# ba[2] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~126}]
# cas -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~49}]
# cke -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~123~1}]
# cs -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~95~1}]
# dm[0] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~131~1}]
# dm[1] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~83~1}]
# dq[0] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~148~1}]
# dq[0] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~150~1}]
# dq[10] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~22~1}]
# dq[10] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~24~1}]
# dq[11] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~92~1}]
# dq[11] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~94~1}]
# dq[12] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~23~1}]
# dq[12] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~25~1}]
# dq[13] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~38~1}]
# dq[13] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~40~1}]
# dq[14] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~11~1}]
# dq[14] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~13~1}]
# dq[15] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~12~1}]
# dq[15] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~14~1}]
# dq[1] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~157~1}]
# dq[1] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~159~1}]
# dq[2] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~164~1}]
# dq[2] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~166~1}]
# dq[3] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~149~1}]
# dq[3] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~151~1}]
# dq[4] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~189~1}]
# dq[4] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~191~1}]
# dq[5] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~156~1}]
# dq[5] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~158~1}]
# dq[6] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~165~1}]
# dq[6] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~167~1}]
# dq[7] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~188~1}]
# dq[7] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~190~1}]
# dq[8] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~82~1}]
# dq[8] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~84~1}]
# dq[9] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~39~1}]
# dq[9] -clock twd_clk -reference_pin [get_ports {twd_clk~CLKOUT~41~1}]
# dqs[0] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~172~1}]
# dqs[0] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~174~1}]
# dqs[0] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~175~1}]
# dqs[1] -clock tac_clk -reference_pin [get_ports {tac_clk~CLKOUT~30~1}]
# dqs[1] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~32~1}]
# dqs[1] -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~33~1}]
# hdmi_rx_d0 -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~258}]
# hdmi_rx_d1 -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~283}]
# hdmi_rx_d2 -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~271}]
# mdc_o -clock clk_10m -reference_pin [get_ports {clk_10m~CLKOUT~1~195}]
# mdc_o1 -clock clk_10m -reference_pin [get_ports {clk_10m~CLKOUT~1~181}]
# odt -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~73~1}]
# ras -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~48}]
# reset -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~139}]
# rx_dv -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~146}]
# rx_dv1 -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~293}]
# rxd1[0] -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~277}]
# rxd1[1] -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~278}]
# rxd1[2] -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~267}]
# rxd1[3] -clock rxc1 -reference_pin [get_ports {rxc1~CLKOUT~1~222}]
# rxd[0] -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~129}]
# rxd[1] -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~113}]
# rxd[2] -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~12}]
# rxd[3] -clock rxc -reference_pin [get_ports {rxc~CLKOUT~1~96}]
# tmds_tx_clk -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~175}]
# tmds_tx_data0 -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~215}]
# tmds_tx_data1 -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~187}]
# tmds_tx_data2 -clock hdmi_rx_slow_clk -reference_pin [get_ports {hdmi_rx_slow_clk~CLKOUT~218~200}]
# tx_en_o -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~15}]
# tx_en_o1 -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~223}]
# txc -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~130}]
# txc1 -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~268}]
# txd1[0] -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~257}]
# txd1[1] -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~245}]
# txd1[2] -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~246}]
# txd1[3] -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~171}]
# txd[0] -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~114}]
# txd[1] -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~97}]
# txd[2] -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~206}]
# txd[3] -clock clk_125m -reference_pin [get_ports {clk_125m~CLKOUT~1~207}]
# we -clock tdqss_clk -reference_pin [get_ports {tdqss_clk~CLKOUT~218~94}]
