// =============================================================================
// Generated by efx_ipmgr
// Version: 2024.2.294
// IP Version: 5.3
// =============================================================================

////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2013-2024 Efinix Inc. All rights reserved.              
//
// This   document  contains  proprietary information  which   is        
// protected by  copyright. All rights  are reserved.  This notice       
// refers to original work by Efinix, Inc. which may be derivitive       
// of other work distributed under license of the authors.  In the       
// case of derivative work, nothing in this notice overrides the         
// original author's license agreement.  Where applicable, the           
// original license agreement is included in it's original               
// unmodified form immediately below this header.                        
//                                                                       
// WARRANTY DISCLAIMER.                                                  
//     THE  DESIGN, CODE, OR INFORMATION ARE PROVIDED “AS IS” AND        
//     EFINIX MAKES NO WARRANTIES, EXPRESS OR IMPLIED WITH               
//     RESPECT THERETO, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES,  
//     INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF          
//     MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR    
//     PURPOSE.  SOME STATES DO NOT ALLOW EXCLUSIONS OF AN IMPLIED       
//     WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO LICENSEE.           
//                                                                       
// LIMITATION OF LIABILITY.                                              
//     NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR BODILY       
//     INJURY, EFINIX SHALL NOT BE LIABLE WITH RESPECT TO ANY SUBJECT    
//     MATTER OF THIS AGREEMENT UNDER TORT, CONTRACT, STRICT LIABILITY   
//     OR ANY OTHER LEGAL OR EQUITABLE THEORY (I) FOR ANY INDIRECT,      
//     SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY    
//     CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF      
//     GOODWILL, DATA OR PROFIT, WORK STOPPAGE, OR COMPUTER FAILURE OR   
//     MALFUNCTION, OR IN ANY EVENT (II) FOR ANY AMOUNT IN EXCESS, IN    
//     THE AGGREGATE, OF THE FEE PAID BY LICENSEE TO EFINIX HEREUNDER    
//     (OR, IF THE FEE HAS BEEN WAIVED, $100), EVEN IF EFINIX SHALL HAVE 
//     BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO 
//     NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR            
//     CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT   
//     APPLY TO LICENSEE.                                                
//
////////////////////////////////////////////////////////////////////////////////

mipi_dsi_rx u_mipi_dsi_rx
(
    .reset_n ( reset_n ),
    .clk ( clk ),
    .reset_byte_HS_n ( reset_byte_HS_n ),
    .clk_byte_HS ( clk_byte_HS ),
    .reset_pixel_n ( reset_pixel_n ),
    .clk_pixel ( clk_pixel ),
    .Rx_LP_CLK_P ( Rx_LP_CLK_P ),
    .Rx_LP_CLK_N ( Rx_LP_CLK_N ),
    .Rx_HS_enable_C ( Rx_HS_enable_C ),
    .LVDS_termen_C ( LVDS_termen_C ),
    .Rx_LP_D_P ( Rx_LP_D_P ),
    .Rx_LP_D_N ( Rx_LP_D_N ),
    .Rx_HS_D_0 ( Rx_HS_D_0 ),
    .Rx_HS_D_1 ( Rx_HS_D_1 ),
    .Rx_HS_D_2 ( Rx_HS_D_2 ),
    .Rx_HS_D_3 ( Rx_HS_D_3 ),
    .Rx_HS_enable_D ( Rx_HS_enable_D ),
    .LVDS_termen_D ( LVDS_termen_D ),
    .fifo_rd_enable ( fifo_rd_enable ),
    .fifo_rd_empty ( fifo_rd_empty ),
    .DLY_enable_D ( DLY_enable_D ),
    .DLY_inc_D ( DLY_inc_D ),
    .u_dly_enable_D ( u_dly_enable_D ),
    .u_dly_inc_D ( u_dly_inc_D ),
    .Tx_LP_D_P ( Tx_LP_D_P ),
    .Tx_LP_D_P_OE ( Tx_LP_D_P_OE ),
    .Tx_LP_D_N ( Tx_LP_D_N ),
    .Tx_LP_D_N_OE ( Tx_LP_D_N_OE ),
    .axi_clk ( axi_clk ),
    .axi_reset_n ( axi_reset_n ),
    .axi_awaddr ( axi_awaddr ),
    .axi_awvalid ( axi_awvalid ),
    .axi_awready ( axi_awready ),
    .axi_wdata ( axi_wdata ),
    .axi_wvalid ( axi_wvalid ),
    .axi_wready ( axi_wready ),
    .axi_bvalid ( axi_bvalid ),
    .axi_bready ( axi_bready ),
    .axi_araddr ( axi_araddr ),
    .axi_arvalid ( axi_arvalid ),
    .axi_arready ( axi_arready ),
    .axi_rdata ( axi_rdata ),
    .axi_rvalid ( axi_rvalid ),
    .axi_rready ( axi_rready ),
    .hsync ( hsync ),
    .vsync ( vsync ),
    .vc ( vc ),
    .word_count ( word_count ),
    .pixel_data ( pixel_data ),
    .pixel_data_valid ( pixel_data_valid ),
    .pixel_vc ( pixel_vc ),
    .pixel_format ( pixel_format ),
    .datatype ( datatype ),
    .video_format ( video_format ),
    .irq ( irq )
);
