
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2025.2.288.3.8
# Date: 2026-03-28 21:07

# Copyright (C) 2013 - 2025 Efinix Inc. All rights reserved.

# Device: Ti60F225
# Project: LED_8bit_Test
# Timing Model: C4 (final)

# Oscillator Constraints
##########################
create_clock -period 12.500 -name osc_clk [get_ports {osc_clk}]

# PLL Constraints
###################
create_clock -waveform {10.000 20.000} -period 20.000 -name clk_50m [get_ports {clk_50m}]
create_clock -period 40.000 -name clk_25m_x2 [get_ports {clk_25m_x2}]
create_clock -waveform {9.260 18.519} -period 18.519 -name clk_54m [get_ports {clk_54m}]

# GPIO Constraints
####################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {key_i[0]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {key_i[0]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {key_i[1]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {key_i[1]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {key_i[2]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {key_i[2]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {key_i[3]}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {key_i[3]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led_data[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led_data[0]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led_data[1]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led_data[1]}]

# HSIO GPIO Constraints
#########################
create_clock -period <USER_PERIOD> -name gpio_clk_25m [get_ports {gpio_clk_25m}]
create_clock -period <USER_PERIOD> -name gpio_clk_27m [get_ports {gpio_clk_27m}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led_data[2]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led_data[2]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led_data[3]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led_data[3]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led_data[4]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led_data[4]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led_data[5]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led_data[5]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led_data[6]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led_data[6]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led_data[7]}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led_data[7]}]

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 1.907> [get_ports {clk_50m}]
# set_clock_latency -source -hold <board_min + 1.271> [get_ports {clk_50m}]
# set_clock_latency -source -setup <board_max + 2.648> [get_ports {clk_54m}]
# set_clock_latency -source -hold <board_min + 1.730> [get_ports {clk_54m}]
# set_clock_latency -source -setup <board_max + 2.622> [get_ports {clk_25m_x2}]
# set_clock_latency -source -hold <board_min + 1.713> [get_ports {clk_25m_x2}]
# set_clock_latency -source -setup <board_max + 0.828> [get_ports {gpio_clk_25m}]
# set_clock_latency -source -hold <board_min + 0.552> [get_ports {gpio_clk_25m}]
# set_clock_latency -source -setup <board_max + 0.828> [get_ports {gpio_clk_27m}]
# set_clock_latency -source -hold <board_min + 0.552> [get_ports {gpio_clk_27m}]
